# Alle hier gesetzten Werte können über `$addon->getProperty($key)` abgefragt werden

package: demo_yorm # Pflichtfeld
version: '1.0.0' # Pflichtfeld
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/demo_yorm

# Seiten
page:
    title: 'translate:title' # Werte die mit `translate:` beginnen, werden anhand der Sprachdatei übersetzt. Der Addon-Präfix (hier `demo_yorm_`) kann weggelassen werden.
    icon: rex-icon fa-shopping-cart
    href: {page: demo_yorm/Product, table_name: rex_product}

    # Unterseiten
    subpages:

        Product:
            title: 'translate:page_product'
            icon: rex-icon fa-info-circle
            perm: demo_yorm[Product]
            subPath: ../yform/plugins/manager/pages/data_edit.php
            href: {page: demo_yorm/Product, table_name: rex_product}

        ProductCategory:
            title: 'translate:page_product_category'
            icon: rex-icon fa-database
            perm: demo_yorm[ProductCategory]
            subPath: ../yform/plugins/manager/pages/data_edit.php
            href: {page: demo_yorm/ProductCategory, table_name: rex_product_category}
            
# Abhängigkeiten
# Anforderungen ans System oder anderere AddOns, um dieses AddOn installieren oder update zu können
requires:
    packages:
        yform: '>=2.0.0' # benötigt mindestens das Addon Media Manager 2.0.1
    
# Plugins die automatisch installiert werden sollen
system_plugins:
    - documentation
