# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: plus_helferlein
version: '0.0.1'
author: alexplus.de
supportpage: https://github.com/alexplusde/PlusHelferlein

page:
    title: 'translate:title'
    perm: plus_helferlein[]
    subpages:
        main: { title: 'translate:main' }
        config: { title: 'translate:config', perm: 'plus_helferlein[config]', icon: rex-icon fa-wrench }

requires:
    redaxo: '>=5.3'
    packages:
        media_manager: '^2.3' 
        yform: '^2.1'
    php:
        version: '>=7' 
        extensions: []
