# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: dummy # Pflichtfeld
version: '1.0' # Pflichtfeld
author: Gregor Harlan
supportpage: www.redaxo.org/de/forum

navigation:
  title: 'translate:title' # Werte die mit "translate:" beginnen, werden anhand der Sprachdatei übersetzt. Der Addon-Präfix (hier "dummy_") kann weggelassen werden.
  perm: dummy[]
  subpages:
    main: {title: 'translate:main'}
    config: {title: 'translate:config', perm: dummy[config]} # config-Seite mit separaten Rechten
