# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: dummy # Pflichtfeld
version: '1.0' # Pflichtfeld
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/dummy

page:
    title: 'translate:title' # Werte die mit "translate:" beginnen, werden anhand der Sprachdatei übersetzt. Der Addon-Präfix (hier "dummy_") kann weggelassen werden.
    perm: dummy[]
    subpages:
        main: { title: 'translate:main' }
        config: { title: 'translate:config', perm: dummy[config] } # config-Seite mit separaten Rechten
